### ISSUE TITLE
File import broken

### ISSUE THREAD

**Issue by nilshg** [iZettle/izettle-toolbox#283]
To reproduce:

1. Download the sample import file from the web interface
2. Fill in a single product/variant name
3. Upload via web interface

While the preview shows the file has been parsed correctly, when clicking import I get an error message saying "only xls and xlsx files supported" - I tried uploading the file in both formats to no avail.

**Comment by pgisslen** [comment]
Will most likely be fixed with the new import/export logic which is currently being rolled out. Hopefully to all customers within a week.

**Comment by nilshg** [comment]
Grateful if you could post here when the roll-out is complete and I'll give it a go!

**Comment by nilshg** [comment]
Have tried this recently - works fine now!

A related question (happy to open another issue if you would consider implementing this) - is there a way to import/export with folder information as well? Currently exports don't give the folder a product is in and I believe imports don't allow adding this information either.
